### ISSUE TITLE
  this[kHandle] = new _Hash(algorithm, xofLen);      ^  Error: error:0308010C:digital envelope routines::unsupported

### ISSUE THREAD

**Issue by scottstensland** [Bonsai-Desk/bonsai-browser#51]
getting

```

git clone git@github.com:Bonsai-Desk/bonsai-browser 

cd /home/ioly/src/github.com/Bonsai-Desk/bonsai-browser

yarn


yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning " > styled-components@5.3.1" has unmet peer dependency "react-is@>= 16.8.0".
warning " > @material-ui/icons@4.11.2" has incorrect peer dependency "@material-ui/core@^4.0.0".
warning "@nozbe/watermelondb > @nozbe/with-observables@1.4.0" has unmet peer dependency "@types/hoist-non-react-statics@^3.3.1".
warning " > react-stonecutter@0.3.10" has incorrect peer dependency "react@^15.3.2 || ^16.0.0".
warning " > react-stonecutter@0.3.10" has incorrect peer dependency "react-dom@^15.3.2 || ^16.0.0".
warning "react-stonecutter > react-motion@0.5.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0".
warning " > browserslist-config-erb@0.0.1" has incorrect peer dependency "electron@^7.0.0".
warning " > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react@^16.0.0-0".
warning " > enzyme-adapter-react-16@1.15.6" has incorrect peer dependency "react-dom@^16.0.0-0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils@1.14.0" has incorrect peer dependency "react@0.13.x || 0.14.x || ^15.0.0-0 || ^16.0.0-0".
warning "enzyme-adapter-react-16 > react-test-renderer@16.14.0" has incorrect peer dependency "react@^16.14.0".
warning "enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0" has incorrect peer dependency "react@^0.14 || ^15.0.0 || ^16.0.0-alpha".
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
$ node -r @babel/register .erb/scripts/CheckNativeDep.js && electron-builder install-app-deps && yarn cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js && opencollective-postinstall && yarn-deduplicate yarn.lock
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
  • electron-builder  version=22.14.5
  • loaded configuration  file=package.json ("build" field)
  • installing production dependencies  platform=linux arch=x64 appDir=/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/src
yarn run v1.22.19
$ /home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/.bin/cross-env NODE_ENV=development webpack --config ./.erb/configs/webpack.config.renderer.dev.dll.babel.js
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at BulkUpdateDecorator.hashFactory (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/util/createHash.js:155:18)
    at BulkUpdateDecorator.update (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/util/createHash.js:46:50)
    at RawSource.updateHash (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/node_modules/webpack-sources/lib/RawSource.js:77:8)
    at NormalModule._initBuildHash (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/NormalModule.js:888:17)
    at handleParseResult (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/NormalModule.js:954:10)
    at /home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/NormalModule.js:1048:4
    at processResult (/home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/NormalModule.js:763:11)
    at /home/ioly/src/github.com/Bonsai-Desk/bonsai-browser/node_modules/webpack/lib/NormalModule.js:827:5 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.3.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.



node --version
v18.3.0



```

this is on fully updated Ubuntu 20.04

**Comment by vorticalbox** [comment]
Read me says it was tested on node 16 currently the lts version have you tried using that?

**Comment by Pictor13** [comment]
He reported:
>node --version
>v18.3.0

https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
https://itsmycode.com/error-digital-envelope-routines-unsupported/

Node version is not LTS and is not supported. Solution is to downgrade or specify legacy openssl version (see links).

**Comment by millette** [comment]
18 is `LTS` since October.

- <https://github.com/nodejs/Release>
- <https://nodejs.org/en/blog/release/v18.12.0/>

Although 16 is supported until [2023-09-11](https://nodejs.org/en/blog/announcements/nodejs16-eol/).
